name: Cypress Tests

on:
  pull_request:
    branches:
      - staging
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Create .env file
        run: |
          echo "DATABASE_URL=postgresql://user:password@localhost:5432/testdb" >> .env
          echo "NEXT_PUBLIC_BASE_URL_API=http://localhost:3000" >> .env

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -U user; do
            echo "Esperando a que PostgreSQL esté listo..."
            sleep 2
          done

      - name: Drop and recreate test database
        run: |
          PGPASSWORD=password psql -h localhost -U user -d postgres -c "DROP DATABASE IF EXISTS testdb;"
          PGPASSWORD=password psql -h localhost -U user -d postgres -c "CREATE DATABASE testdb;"

      - name: List migration files
        run: ls -l src/infrastructure/database/migrations

      - name: Run SQL migrations
        run: |
          for f in src/infrastructure/database/migrations/*.sql; do
            PGPASSWORD=password psql -h localhost -U user -d testdb -f "$f"
          done

      - name: Insert test data into PostgreSQL
        run: |
          PGPASSWORD=password psql -h localhost -U user -d testdb -c "
            INSERT INTO influencers (username, profile_name, profile_picture, profile_url, average_likes, average_comments, average_shares, average_saves, average_views, followers, city, featured_videos, status)
            VALUES 
            ('allaccesscolombia', 'All Access Colombia', 'https://p16-sign-va.tiktokcdn.com/tos-maliva-avt-0068/b55f28eeae54d50c18a486a6f0eaf17a~tplv-tiktokx-cropcenter:1080:1080.jpeg?dr=14579&refresh_token=414690f7&x-expires=1745607600&x-signature=uptMLjNhS1OElwmHoDGbgrVGhII%3D&t=4d5b0474&ps=13740610&shp=a5d48078&shcp=81f88b70&idc=maliva', 
            'https://www.tiktok.com/@allaccesscolombia', 762.1, 38.4, 88, 61.4, 18764.9, 16300, 'Medellín', '["7298163366957272326","7254017244424899845","7253892153544428806"]', 'inactive');

            INSERT INTO messages (content)
            VALUES 
            ('Hi, we came across your profile and were really impressed by your content! We believe your influence could be a great fit for promoting job opportunities. We''d love to collaborate with you - let us know if you''re interested!');

            INSERT INTO users (email, password, name) 
            VALUES 
            ('testuser@email.com', '$2b$10$DLNNCcxtJ2.MIyKNdg9TA.PGvc/TmGkLmq6btjSq/abWHBUJ/63Oa', 'TestLoginUser');
          "

      - name: Start the development server
        run: |
          nohup npm run dev &

      - name: Wait for the application to be ready
        run: |
          until curl -s http://localhost:3000 > /dev/null; do
            echo "Esperando a que el servidor esté listo..."
            sleep 2
          done

      - name: Run Cypress tests
        run: npx cypress run